Created axios
fullstacktf/fs5-gestiondesocios-frontend pull request #51
Opened 2020-12-12 18:22 UTC by Joaqmn

2020-12-13 12:14 UTC, dd8888 requested changes

2020-12-13 12:14 UTC, dd8888 commented on src/domain/services/assocPartnersServices.js
> +export const insertPartner = async (id) => {
A los métodos insert y update hay que enviarle un body también

2020-12-13 12:14 UTC, dd8888 commented on src/utils/assoc_partners.js
> +  async updatePartner(ID) {
Es put el método para hacer update

2020-12-13 15:46 UTC, Joaqmn commented on src/domain/services/assocPartnersServices.js
> +export const insertPartner = async (id) => {
Debería de estar ya.

2020-12-13 15:47 UTC, Joaqmn commented on src/utils/assoc_partners.js
> +  async updatePartner(ID) {
Corregido.

2020-12-13 15:51 UTC, dd8888 requested changes

2020-12-13 15:51 UTC, dd8888 commented on src/domain/services/borrowedGamesServices.js
> +export const insertBorrowedGames = async (id) => {
Aquí hace falta body también

2020-12-13 15:51 UTC, dd8888 commented on src/domain/services/gamesServices.js
> +export const insertGame = async (id) => {
Y en estoy hace falta body pero en mi rama ya lo tengo da igual

2020-12-13 15:52 UTC, dd8888 commented
- Todos los put y post suelen llevar body.
- En los métodos que reciban "ID" en minúscula pls.

2020-12-14 09:38 UTC, raulanatol commented on src/domain/services/assocPartnersServices.js
> +import Partners from "../../utils/assoc_partners";
Cuiden los nombres de los ficheros assoc_partners no se suele usar _ como nombre de fichero.
Y la palabra **assoc** la veo redundante ya que es la web de una asociación, pienso que no aporta valor.

2020-12-14 09:41 UTC, raulanatol commented on src/domain/services/borrowedGamesServices.js
> +export const getBorrowedGames = async () => {
Al igual que en el comentario anterior. Si ya estamos en servicios de BorrowedGames la el prefijo me resulta redundante.

Ejemplo: 
	`borrowedGames.insertBorrowedGames`
	`game.insertGame`

Lo más importante de los nombres es que aporten valor para cuando se lean, es como los comentarios de tipo:

/**
 * Insert a Game
 * @params id: game Id
 * @params body: game body
 */
export const insertGame = async (id, body) => {

2020-12-14 09:46 UTC, raulanatol commented on src/utils/borrowed_games.js
> +      .get("https://api.chimaera.games/api/borrowedgames")
La url la usan mucho qué pasaría si decidiéramos usar una versión de stage?

Lo mejor en esos casos es tirar de variable al estilo:
```js
const basePath='https://api.chimaera.games/api';
```

Y luego ir concatenando.

```suggestion
      .get(`${basePath}/borrowedgames`)
```

Es más axios tiene un modelo diseñado para esto.

2020-12-14 09:46 UTC, raulanatol submitted a review, later dismissed

2020-12-14 13:01 UTC, dd8888 approved these changes

2020-12-14 13:04 UTC, merged