docs: ✏️ Updated axios in docs
fullstacktf/fs5-gestiondesocios-frontend pull request #60
Opened 2020-12-15 14:21 UTC by Joaqmn

2020-12-15 14:29 UTC, dd8888 requested changes
Van sin el return await, solo la llamada a axios

2020-12-16 07:29 UTC, yodra approved these changes

2020-12-16 07:40 UTC, JuanDaniel2510 approved these changes

2020-12-16 10:55 UTC, dd8888 approved these changes
Va con el path completo pero da igual lo arreglamos si hay tiempo

2020-12-16 22:00 UTC, merged